name: Build Debian Package

on:
  push:
    branches:
      - main
    paths:
      - "debian/"
      - ".sh"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04

    steps:
      - name: Set Timezone to Kyiv
        run: |
          ln -sf /usr/share/zoneinfo/Europe/Kiev /etc/localtime
          echo "Europe/Kiev" > /etc/timezone
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Debian
        run: |
          mkdir testos && mkdir testos/DEBIAN
          mkdir -p testos/usr/local/bin
          cp calc_files.sh testos/usr/local/bin/
          cp debian/control testos/DEBIAN
          dpkg-deb --build testos
          dpkg -i testos.deb
          chmod +x /usr/local/bin/calc_files.sh

      - name: Upload Debian
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: |
            ~/*.deb

