name: Build RPM Package

on:
  push:
    branches:
      - main
    paths:
      - 'rpm/.spec'
      - '.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04

    steps:
      - name: Set Timezone to Kyiv
        run: |
          ln -sf /usr/share/zoneinfo/Europe/Kiev /etc/localtime
          echo "Europe/Kiev" > /etc/timezone
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install RPM build tools
        run: |
          apt-get update
          apt-get install -y rpm wget unzip
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

      - name: Build RPM
        run: |
          # Убедитесь, что директории существуют
          mkdir -p ~/rpmbuild/SPECS
          mkdir -p ~/rpmbuild/SOURCES
          cp rpm/calcfiles.spec ~/rpmbuild/SPECS/
          cd ~/rpmbuild/SOURCES/
          wget https://github.com/Maxrule/Systema/archive/main.zip
          unzip main.zip
          cd Systema-main/
          rpmbuild -bs --define "dist .generic" ~/rpmbuild/SPECS/calcfiles.spec
          rpmbuild --rebuild ~/rpmbuild/SRPMS/calcfiles-1.0-1.generic.src.rpm

      - name: Upload RPM
        uses: actions/upload-artifact@v3
        with:
          name: rpm-package
          path: |
            ~/rpmbuild/RPMS/*.rpm
            ~/rpmbuild/SRPMS/*.src.rpm
            
